title: <p align="center">Venu Madhav Kolloju</p>
logo: /assets/img/profile.png
description: This is Venu Madhav Kolloju GitHub Page.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
